name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку, если она не main

permissions:
  contents: write  # Права для записи в репозиторий
  pages: write     # Права для деплоя на GitHub Pages
  id-token: write  # Права для работы с токенами

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          cd cv
          npm ci
          npm run build

      - name: List build folder
        run: |
          ls -la cv/build  # Если ваши файлы в cv/build
          ls -la cv/static  # Если ваши файлы в cv/static


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cv/build  # Путь к папке с результатами сборки (cv/static)
